{
 "title": "Purestorage Array - Prometheus",
 "tags": [
  "Purestorage",
  "FlashArrays"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "fa", "query": "label_values(array)" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array)(array_power{array=~\"[[fa]]\"})"
    }
   ]
  },
  {
   "title": "Critical Events",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array)(purestorage_events_total{array=~\"[[fa]]\", severity=\"critical\"})"
    }
   ]
  },
  {
   "title": "Warning Events",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array)(purestorage_events_total{array=~\"[[fa]]\", severity=\"warning\"})"
    }
   ]
  },
  {
   "title": "Info Events",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array)(purestorage_events_total{array=~\"[[fa]]\", severity=\"info\"})"
    }
   ]
  },
  {
   "title": "Temperature Controller 0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_temperature{array=~\"[[fa]]\", hw=~\"CT0.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "Temperature Controller 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_temperature{array=~\"[[fa]]\", hw=~\"CT1.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Bays",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CH0_BAY.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  NVM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CH0_NVB.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Controller 0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CT0\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Controller 0 Eth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CT0_ETH.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Controller 0 FAN",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CT0_FAN.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Controller 0 Temp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CT0_TMP.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Controller 0 SAS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CT0_SAS.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Controller 1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CT1\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Controller 1 Eth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CT1_ETH.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Controller 1 FAN",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CT1_FAN.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Controller 1 Temp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CT1_TMP.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  {
   "title": "HW Status  Controller 1 SAS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, hw)(array_hw_status{array=~\"[[fa]]\", hw=~\"CT1_SAS.*\"})",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[fa]]\"})",
     "legendFormat": "input",
     "target": "highestAverage(groupByNode(storage.purestorage.$PureSystems.array_stats.*put_per_sec, 2, 'sum'), $TopResources)"
    },
    {
     "expr": "max by (array)(purestorage_array_perf_output_per_sec{array=\"[[fa]]\"})",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 38 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "max by (array)(purestorage_array_perf_reads_per_sec{array=~\"[[fa]]\"})",
     "legendFormat": "reads",
     "target": "max by (array)(purestorage_array_perf_input_per_sec{array=\"[[array]]\"})"
    },
    {
     "expr": "max by (array)(purestorage_array_perf_writes_per_sec{array=~\"[[fa]]\"})",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 38 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max by(array)(purestorage_array_perf_usec_per_read_op{array=~\"[[fa]]\"})",
     "legendFormat": "reads",
     "target": "highestAverage(groupByNode(storage.purestorage.$PureSystems.array_stats.*usec_per_*_op, 4, 'avg'), $TopResources)"
    },
    {
     "expr": "max by(array)(purestorage_array_perf_usec_per_write_op{array=~\"[[fa]]\"})",
     "legendFormat": "writes"
    },
    {
     "expr": "max by(array)(purestorage_array_perf_san_usec_per_read_op{array=~\"[[fa]]\"})",
     "legendFormat": "san_reads"
    },
    {
     "expr": "max by(array)(purestorage_array_perf_san_usec_per_write_op{array=~\"[[fa]]\"})",
     "legendFormat": "san_writes"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array)(purestorage_array_perf_queue_depth{array=~\"[[fa]]\"})"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Thin Provisioning",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array)(purestorage_array_space_thin_provisioning{array=~\"[[fa]]\"})"
    }
   ]
  },
  {
   "title": "Array Capacity",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 47 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array)(purestorage_array_space_capacity{array=~\"[[fa]]\"})"
    }
   ]
  },
  {
   "title": "Parity",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array)(purestorage_array_space_parity{array=~\"[[fa]]\"})"
    }
   ]
  },
  {
   "title": "Total Reduction",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array)(purestorage_array_space_total_reduction{array=~\"[[fa]]\"})"
    }
   ]
  },
  {
   "title": "Data Reduction",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array)(purestorage_array_space_data_reduction{array=~\"[[fa]]\"})"
    }
   ]
  },
  {
   "title": "Space Overview",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by(array)(purestorage_array_space_shared_space{array=~\"[[fa]]\"})",
     "legendFormat": "shared",
     "target": "highestAverage(groupByNode(storage.purestorage.$PureSystems.array_stats.total, 2, 'sum'), $TopResources)"
    },
    {
     "expr": "max by(array)(purestorage_array_space_provisioned{array=~\"[[fa]]\"})",
     "legendFormat": "provisioned"
    },
    {
     "expr": "max by(array)(purestorage_array_space_snapshots{array=~\"[[fa]]\"})",
     "legendFormat": "snapshots"
    },
    {
     "expr": "max by(array)(purestorage_array_space_volumes{array=~\"[[fa]]\"})",
     "legendFormat": "volume"
    },
    {
     "expr": "max by(array)(purestorage_array_space_system{array=~\"[[fa]]\"})",
     "legendFormat": "system"
    },
    {
     "expr": "max by(array)(purestorage_array_space_total{array=~\"[[fa]]\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}