{
 "title": "Prometheus Exporter",
 "tags": [
  "Purestorage",
  "Flasharray"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "dc", "query": "label_values(data_center)" },
   { "name": "exporter", "label": "exporter", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$exporter CPU seconds Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=~\"[[exporter]]\", data_center=~\"[[dc]]\"}"
    }
   ]
  },
  {
   "title": "Running $exporter Exporters",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by(data_center, job)(process_cpu_seconds_total{job=~\"[[exporter]]\", data_center=\"[[dc]]\"})"
    }
   ]
  },
  {
   "title": "$exporter  Start Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~\"[[exporter]]\", data_center=~\"[[dc]]\"} *1000"
    }
   ]
  },
  {
   "title": "$exporter Resident Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"[[exporter]]\", data_center=~\"[[dc]]\"}"
    }
   ]
  },
  {
   "title": "$exporter file descriptors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{job=~\"[[exporter]]\", data_center=~\"[[dc]]\"}",
     "legendFormat": "max"
    },
    {
     "expr": "process_open_fds{job=~\"[[exporter]]\", data_center=~\"[[dc]]\"}",
     "legendFormat": "open"
    }
   ]
  }
 ]
}