{
 "title": "Purestorage: Volumes Prometheus",
 "tags": [
  "Purestorage",
  "Flasharray"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "fa", "query": "label_values(array)" },
   {
    "name": "vol",
    "query": "label_values({array=~\"$fa\"}, volume)"
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency (array to initiator)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max by(array, volume)(purestorage_vol_perf_san_usec_per_read_op{volume=~\"[[vol]]\"})",
     "legendFormat": "reads",
     "target": "aliasByNode(storage.purestorage.$PureSystems.volume_stats.$VolName.san_usec_per_read_op, 2, 4)"
    },
    {
     "expr": "max by(array, volume)(purestorage_vol_perf_san_usec_per_write_op{volume=~\"[[vol]]\"})",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Latency (arrival to completion)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max by(array, volume)(purestorage_vol_perf_usec_per_read_op{volume=~\"[[vol]]\"})",
     "legendFormat": "reads",
     "target": "aliasByNode(sortByMaxima(highestAverage(storage.purestorage.$PureSystems.volume_stats.$VolName.usec_per_read_op, $TopResources)), 2, 4)"
    },
    {
     "expr": "max by(array, volume)(purestorage_vol_perf_usec_per_write_op{volume=~\"[[vol]]\"})",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max by(array, volume)(purestorage_vol_perf_input_per_sec{volume=~\"[[vol]]\"})",
     "legendFormat": "input",
     "target": "aliasByNode(sortByMaxima(highestAverage(storage.purestorage.$PureSystems.volume_stats.$VolName.output_per_sec, $TopResources)), 2, 4)"
    },
    {
     "expr": "max by(array, volume)(purestorage_vol_perf_output_per_sec{volume=~\"[[vol]]\"})",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(array, volume)(purestorage_vol_perf_reads_per_sec{volume=~\"[[vol]]\"})",
     "legendFormat": "reads"
    },
    {
     "expr": "max by(array, volume)(purestorage_vol_perf_writes_per_sec{volume=~\"[[vol]]\"})"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Size",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array, volume)(purestorage_vol_space_size{volume=~\"[[vol]]\"})"
    }
   ]
  },
  {
   "title": "Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by(array, volume)(purestorage_vol_space_volumes{volume=~\"[[vol]]\"})",
     "legendFormat": "volume",
     "target": "aliasByNode(sortByMaxima(highestAverage(storage.purestorage.$PureSystems.volume_stats.$VolName.total, $TopResources)), 2, 4)"
    },
    {
     "expr": "max by(array, volume)(purestorage_vol_space_snapshots{volume=~\"[[vol]]\"})",
     "legendFormat": "snapshots"
    },
    {
     "expr": "max by(array, volume)(purestorage_vol_space_total{volume=\"[[vol]]\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Reductiton",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array, volume)(purestorage_vol_space_total_reduction{volume=\"[[vol]]\"})"
    }
   ]
  },
  {
   "title": "Data reduction",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array, volume)(purestorage_vol_space_data_reduction{volume=\"[[vol]]\"})"
    }
   ]
  },
  {
   "title": "Thin Provisioning",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by(array, volume)(purestorage_vol_space_thin_provisioning{volume=~\"[[vol]]\"})"
    }
   ]
  }
 ]
}